# ASP.NET

# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: UseNode@1
  inputs:
    checkLatest: true
- task: Npm@1
  inputs:
    command: 'install'
    workingDir: 'samples/js/ACS_Calling_Sample/ClientApp'
- task: Npm@1
  inputs:
    command: 'custom'
    workingDir: 'samples/js/ACS_Calling_Sample/ClientApp'
    customCommand: 'run build:prod'
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: 'samples/js/ACS_Calling_Sample/Service.NET/ServiceSampleDotNet.csproj'
    arguments: '-c Release'